### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by cliff-wakefield** [srozzo/puppet-stunnel#1]
> $ puppet module install srozzo-stunnel --modulepath /etc/puppetlabs/code/environments/cwakefield/modules/
> Notice: Preparing to install into /etc/puppetlabs/code/environments/cwakefield/modules ...
> Notice: Downloading from https://forgeapi.puppetlabs.com ...
> Error: Could not install module 'srozzo-stunnel' (???)
>   No version of 'srozzo-stunnel' can satisfy all dependencies
>     Use 'puppet module install --ignore-dependencies' to install only this module

**Comment by cliff-wakefield** [comment]
`
[Librarian] Resolving srozzo-stunnel (>= 0) <https://forgeapi.puppetlabs.com>
[Librarian]   Checking manifests
[Librarian]   Module srozzo-stunnel found versions: 1.0.1
[Librarian]     Checking srozzo-stunnel/1.0.1 <https://forgeapi.puppetlabs.com>
[Librarian]       Resolved srozzo-stunnel (>= 0) <https://forgeapi.puppetlabs.com> at srozzo-stunnel/1.0.1 <https://forgeapi.puppetlabs.com>
[Librarian]   Resolved srozzo-stunnel (>= 0) <https://forgeapi.puppetlabs.com>
[Librarian] Resolving electrical-file_concat (~> 1.0) <(no source specified)>
[Librarian]   Checking manifests
[Librarian]   Module electrical-file_concat found versions: 1.0.1, 1.0.0
[Librarian]     Checking electrical-file_concat/1.0.1 <https://forgeapi.puppetlabs.com>
[Librarian]       Resolved electrical-file_concat (~> 1.0) <(no source specified)> at electrical-file_concat/1.0.1 <https://forgeapi.puppetlabs.com>
[Librarian]   Resolved electrical-file_concat (~> 1.0) <(no source specified)>
[Librarian] Conflict between puppetlabs-concat (~> 1.0) <(no source specified)> and puppetlabs-concat/2.2.0 <https://forgeapi.puppetlabs.com>
Could not resolve the dependencies.
`

So it appears to be a conflict between `electrical-file_concat` and `puppetlabs-concat` as you might expect?

Is there a reason you aren't using the puppetlabs version?

Surely others must run into this?

**Comment by cliff-wakefield** [comment]
Looks like your module requires puppetlabs-contcat 1.x

From `metadata.json`
>    {
>       "name": "puppetlabs/concat",
>       "version_requirement": "1.x"
>     },

but latest versions of puppet have puppetlabs-contcat 2.x

**Comment by cliff-wakefield** [comment]
I've submitted a pull request that allows puppetlabs-concat 2.x to be used.

**Comment by srozzo** [comment]
Merged.

**Comment by cliff-wakefield** [comment]
Excellent

**Comment by cliff-wakefield** [comment]
Will you be making a new release and pushing to Puppet Forge.

At the moment I am having to use github directly but would prefer not to.
